language: java
jdk: oraclejdk8
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
     - secure: grJrPYgXgOQGCrFuD99vExUAbfEGo6h1AdNfBV86MS35z8o5kRE76/OguoEzL/ZoishAmX9J4b3yk0oUeeJsGfbdi4ws295lzugVpkCsDgHdlV0ILEUdwlT5yuIK4P/3/XeGa6gl9m2SkoDPolfQjg9QKsEOOmk/qpk59L2HTXvn++nItQ/PPF8cThYRyJW1+XEPxyUtdU8q1tqdygFPvjZK64B4OgM/KueHFuSXekHU8oEOOKqKYljhLV/vEnWdwVG0NG4eF0Ohf6U3nt+Z9Ld4fl0k+Bob86Pm1QC4LvF3ZVQoC3+5rLyNZh28aCfKMIKwmbdsvf0uJjqmKQVO0rSOPPtQ7K4iDZ9xq/0DmLZUCeOhm6MsrbbA6vm0xIcWjMpp4ARpd/jtk/hJ6FXJUUT/yk659Exi7aXtizP5F4wfwDTYUdQE+2Nu7poE/6ST0fdFW1f/nyT0sRyJjtTw+L/354p5t380Mxz5bMZ7hr19ARgkcDVd36iP46MJJAQ5B3AeqxEriocyu1s1gnLBctPgXKcjcjWVMtwaPov9/xg4Aab0mwyNUKbg7seuDuAd9DV61VI6QOqvx27ajyFof04GvRwqOfoqQXcqK4WdmV+Fi91Dkjo4FT0CItmJ1XO2kxDIw32JQfDPQVIfsjmRQcbs7Fb7by5dpGAm33grXvM=
