language: java
jdk: oraclejdk8
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      - secure: XramQReC6BUiwk5BktyccF1A18o13Tagw58V2sxzioOAuSSp3zAOgSe4j0ofFftKTXCtbfb9FulEbjcdCQpNRp8gQXC9fRSqXgAs41C3GRWT5cENxKtL1GixXgDgeWYaYTZs30KwhC1xCMHX/8o5x34Mp3yOmYRMR7Y6B6155pRzKzohmOpF1yRF9irBM2pq4C8Jj2Aii5TqXx5+NDQS06e2eAPkMFj/iEmns7FN9oINvSIGKjLFdGqDGLtcifFkpkt1s4hVnCzJ1msy0ERqGb45hUVx8jfBVoUpe7TpAwwtW1+aw6uaX2UAFtmmuZCdP6nqoIyWUPk5t6OAWa8vOjGZhJF80XGE/RuLreqXd0FNFzZyIiyC8KlxffCFxp/1/LNuG3pAHAVhpH6JR1OjFYN0VPqyzP2LWrF7J+85/KLKDvAA8JnVS7FpwD6u5c29aQz8evwaG+HBUFIrDIOiM3hUKeTEoVkx9yrOZwRD4F7Uvuo7lPwt1cLUkXkKU2FUg92B1JXxJdZ/F3fW/HAu3lXKgExRJfVxapmrSxX2yDyihv4Qqytb5jUdRwF3iIVxxc/CpeWPX5kxhJpa8ikt+mrVWUyD4qAuOPbaLFeRU+6/BB/cQqXADTMLB8WoS8kD/0eO8C6CFEwJKfUIb6OpP56Ej/tirL1fjIEi2BIDplU=
